# Generated by Django 4.0.6 on 2022-08-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('thumbnails', models.JSONField(blank=True, default=dict)),
                ('channelId', models.CharField(blank=True, max_length=256)),
                ('channelTitle', models.TextField(blank=True)),
                ('publishTime', models.DateTimeField()),
            ],
        ),
    ]
